server:
  port: 8088
spring:
  application:
    name: h2lc
  datasource:
    url: jdbc:postgresql://localhost:5432/h2lcdb
    username: h2lcuser
    password: h2lcpass
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        cache:
          use_second_level_cache: true
          region:
            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
          hazelcast:
            use_native_client: true
