services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: h2lcdb
      POSTGRES_USER: h2lcuser
      POSTGRES_PASSWORD: h2lcpass
    ports:
      - 5432:5432
